default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: development
  username: root
  password: PocketPlay
  host: localhost

test:
  <<: *default
  adapter: sqlite3
  database: ':memory:'
