production: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test
