# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e2c2bc07f03b78bdfe6c281345679cb9c6abebba408a18296f8c686994372d5eeea53c6dbc2d5368765df41894c1de5069219a6d2fc76f6c2648728ba623b3

test:
  secret_key_base: 2af920a4cf7aff56cd0dabbd25ecce506c09827b3d0870380d9f68f79252e6dce023691c1cba1979c48dc3308e3fcc438fd3d4fa5b1cf830de31d74378ed2082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
